name: Selenium Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Check directory
        run: | 
          ls -a
      - name: Build with Maven
        run: | 
          cd /Users/runner/work/
          ls -a
          mvn -B package --file pom.xml
      - name: Run tests
        run: mvn test --file pom.xml